#!/usr/bin/env bash
#
# @(#) bootstrap-reverse-tunnel-server
#
# SYNOPSIS
#     bootstrap-reverse-tunnel-server [user]
#
# DESCRIPTION
#     This script installs reverse-tunnel-server. Nodejs is installed
#     via the asdf version manager as needed.
#
: ${CAT_CMD:='/bin/cat'}
: ${GIT_CMD:='/usr/bin/git'}
: ${GREP_CMD:='/bin/grep'}
: ${MV_CMD:='/bin/mv'}
: ${READLINK_CMD:='/bin/readlink'}
: ${RM_CMD:='/bin/rm'}
: ${SUDO_CMD:='/usr/bin/sudo'}

 : ${LOCK:=''}

# OS-agnstoic readlink for existent files/directories.
resolve-existing ()
{
    if $READLINK_CMD --version 2>&1 | $GREP_CMD -q 'coreutils'; then
        $READLINK_CMD -e "$@"
    else
        $READLINK_CMD -f N "$@"
    fi
}

initialize-asdf-env ()
{
    unset -f asdf
    hash -r
    if test -f "${HOME}/.tool-versions"; then
        $MV_CMD "${HOME}/.tool-versions" "${HOME}/.tool-versions.old" || return $?
    fi

    if test ! -f ~/.bashrc || ! $GREP_CMD -q ASDF_DATA_DIR ~/.bashrc; then
        echo "Appending to bashrc..." >&2

        $CAT_CMD >>~/.bashrc <<'EOF'
# Initialize asdf version manager.
: ${ASDF_DATA_DIR:="${HOME}/.asdf"}

unset -f asdf
hash -r
if test -d "${ASDF_DATA_DIR}/shims"; then
    export PATH=${ASDF_DATA_DIR}/shims:$PATH
fi

if command -v asdf >/dev/null; then
    source <(asdf completion bash)
fi
EOF
    fi

    export ASDF_DATA_DIR=${HOME}/.asdf
    export PATH=${ASDF_DATA_DIR}/shims:$PATH
}

nodejs-locally-installed ()
{
    if asdf plugin list | $GREP_CMD -q nodejs; then
        asdf plugin update nodejs &>/dev/null || return $?
        if asdf which go &>/dev/null; then
            return 0
        else
            return 1
        fi
    else
        asdf plugin add nodejs &>/dev/null || return $?
        return 1
    fi
}

install-nodejs ()
{
    local node_base=$1

    echo "Installing nodejs..."

    local latest=''

    latest=$(asdf latest nodejs "$node_base") || return $?
    asdf install nodejs "$latest" || return $?
    (cd ~ && asdf set nodejs "$latest") || return $?
    asdf reshim nodejs || return $?
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=''
    declare script_dir=''

    script=$(resolve-existing "$0") || exit $?
    script_dir=${script%/*}

    declare user=${1:-$USER}
    declare node_base=${2:-'22'}

    # Run script as given user.
    if test ."$LOCKED" != ."$script"; then
        exec env LOCKED="$script" $SUDO_CMD -i -u "$user" \
             --preserve-env=LOCKED "$script" "$@"
    fi

    initialize-asdf-env || exit $?

    if ! nodejs-locally-installed; then
        install-nodejs "$node_base" || exit $?
    fi

    $SUDO_CMD ${script_dir}/install-reverse-tunnel-server || exit $?
fi
