#!/usr/bin/env bash
#
# @(#) install-reverse-tunnel-server
#
# SYNOPSIS
#     install-reverse-tunnel-server [ca-url fingerprint]
#
# DESCRIPTION
#     This script installs in the home directory of user $NODE_USER:
#        1) version manager `asdf',
#        2) the latest version of nodejs in the $NODE_BASE series,
#        3) npm package `reverse-tunnel-server',
#     and finally, if a CA-URL and associated FINGERPRINT are
#     specified, the given certificate authority is bootstraped,
#     otherwise ca.revo.io is bootstraped.
#
# Edit these ...
: ${NODE_BASE:='@NODE_BASE@'}
: ${NODE_GROUP:='@NODE_GROUP@'}
: ${NODE_USER:='@NODE_USER@'}

# Command paths
: ${AWK:='/usr/bin/awk'}
: ${BASH:='/bin/bash'}
: ${CHMOD:='/bin/chmod'}
: ${CHOWN:='/bin/chown'}
: ${CAT:='/bin/cat'}
: ${CURL:='/usr/bin/curl'}
: ${CUT:='/usr/bin/cut'}
: ${GETENT:='/usr/bin/getent'}
: ${GIT:='/usr/bin/git'}
: ${GREP:='/bin/grep'}
: ${INSTALL:='/usr/bin/install'}
: ${READLINK:='/bin/readlink'}
: ${RM:='/bin/rm'}
: ${SED:='/bin/sed'}
: ${SCRIPT:='/usr/bin/script'}
: ${SORT:='/usr/bin/sort'}
: ${STEP_CLI:='/usr/bin/step'}
: ${SUDO:='/usr/bin/sudo'}
: ${TAIL:='/usr/bin/tail'}
: ${TAR:='/bin/tar'}

: ${LOCK:=''}

declare script=$($READLINK -e $0)

# fetch-remote-access-server: Must be called by user `root'.
fetch-remote-access-server ()
{
    local uri_prefix=$1

    local latest=$(
        $CURL -s "${uri_prefix}/reverse-tunnel-server-latest.tgz"
          )
    local node_user_dir=$(
        $GETENT passwd "$NODE_USER" |
            $CUT -d: -f6
          )

    $CURL -Lo "${node_user_dir}/${latest}" "${uri_prefix}/${latest}"
    $TAR -C "$node_user_dir" -zxf "${node_user_dir}/reverse-tunnel-server"*.tgz
    $INSTALL -m 0644 "${node_user_dir}/package/config/reverse-tunnel"  \
             /etc/default
    $INSTALL -m 0644 "${node_user_dir}/package/scripts/reverse-tunnel@.service"  \
             /lib/systemd/system
    $INSTALL -d -m 0755 ~/.ssh

    local statedir=$(
        $AWK  '/^API_STATE_DIR/ { print $NF }' /etc/default/reverse-tunnel
            )

    $INSTALL -d -m 0755 -o "$NODE_USER" -g "$NODE_GROUP" \
             "${statedir}"/{certs,config}
    $INSTALL -d -m 0700 -o "$NODE_USER" -g "$NODE_GROUP" \
             "${statedir}/secrets"

    $RM -rf "${node_user_dir}/package"
}

fetch-asdf ()
{
    if test -d ~/.asdf; then
        $GIT -C ~/.asdf pull
    else
        $GIT clone https://github.com/asdf-vm/asdf.git ~/.asdf
    fi
}

source-asdf ()
{
    source ~/.asdf/asdf.sh
    if ! $GREP -q ASDF_DIR ~/.bashrc; then
        echo "Appending to bashrc..."
        $CAT >>~/.bashrc <<'EOF'

# Initialize asdf version manager.
export ASDF_DIR=~/.asdf
if test -f "${ASDF_DIR}/asdf.sh"; then
    source "${ASDF_DIR}/asdf.sh"
    source "${ASDF_DIR}/completions/asdf.bash"
fi
EOF
    fi
}

install-node ()
{
    if type asdf >/dev/null 2>&1; then
        echo "Installing node..."
        asdf plugin add nodejs || true

        local node_lts=$(
            asdf latest nodejs "$NODE_BASE"
                )

        asdf install nodejs "$node_lts"
        asdf global  nodejs "$node_lts"
        npm i -g npm
        asdf reshim nodejs
    fi
}

install-remote-access-server ()
{
    $INSTALL -d -m 0755 ~/.ssh

    if test -f ~/reverse-tunnel-server*.tgz; then
        npm i -g ~/reverse-tunnel-server*.tgz
        asdf reshim nodejs

        $RM -f ~/reverse-tunnel-server*.tgz
    fi
}

bootstrap-ca ()
{
    local ca_url=$1
    local fingerprint=$2

    $STEP_CLI ca bootstrap --ca-url "$ca_url" --fingerprint "$fingerprint"
    $INSTALL -d -m 0700 ~/.step/secrets
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare ca_url=$1
    declare fingerprint=$2

    if test ."$LOCKED" != ."$script"; then
        if (( EUID != 0 )); then
            echo "${script##*/}: Must be run by user root" >&2
            exit 1
        fi

        declare uri_prefix=https://raw.githubusercontent.com/revolution-robotics/roadrunner-debian/debian_buster_rr01/revo/resources/reverse-tunnel-server

        fetch-remote-access-server "$uri_prefix"

        # Run remainder of script as user $NODE_USER.
        exec env LOCKED="$script" $SUDO -i -u "$NODE_USER" \
             --preserve-env=LOCKED "$script" "$@"
    fi

    fetch-asdf
    source-asdf
    install-node
    install-remote-access-server
    bootstrap-ca "$ca_url" "$fingerprint"
fi
