#!/usr/bin/env bash
#
# @(#) provision-edge-certificate
#
# SYNOPSIS
#     provision-edge-certificate ssh-host [certificate-lifetime]
#
# DESCRIPTION
#
#     This script issues and installs revo.io certificates to a
#     connected edge device. The device and certificate must be separately
#     added to revo.io's database before connecting to revo.io.
#
#     It's assumed that ~/.ssh/config contains entries of the form:
#
#        Host ssh-host
#            Hostname revoedge-f0bb05.local
#            User root
#
#        Host cloudapi
#            Hostname cloudapi.revo.io
#            User revo
#
#    It's further assumed that a local SSH key has been copied to
#    ssh-host (and cloudapi), e.g., via:
#
#        ssh-keyscan revoedge-f0bb05.local >>~/.known_hosts
#        ssh-copy-id ssh-host
#

# Exit immediately on errors.
set -e -o pipefail

: ${AWK:='/usr/bin/awk'}
: ${SSH:='/usr/bin/ssh'}
: ${SCP:='/usr/bin/scp'}

sship ()
{
    local ssh_host=$1

    $SSH -G "$ssh_host" | $AWK '/^hostname/ { printf $2 }'
}

issue-certificate ()
{
    local ssh_host=$1
    local duration=${2:-'9552h'}

    local fqdn=$(sship "$ssh_host")

    $SSH cloudapi "issue-tls-certificate -f $fqdn -d $duration"
}

install-certificate ()
{
    local ssh_host=$1

    local fqdn=$(sship "$ssh_host")
    local host=${fqdn%%.*}

    $SCP -3 cloudapi:~step/.step/issued/${fqdn}.crt \
         ${ssh_host}:~revo/.step/certs
    $SCP -3 cloudapi:~step/.step/issued/${fqdn}.key \
         ${ssh_host}:~revo/.step/secrets
    $SSH "$ssh_host" 'chown revo:revo ~revo/.step/{certs,secrets}/*'
    $SSH "$ssh_host" 'chmod 0600 ~revo/.step/secrets/*'
    $SSH "$ssh_host" "ln -s ${fqdn}.crt ~revo/.step/certs/${host}.crt"
    $SSH "$ssh_host" "ln -s ${fqdn}.key ~revo/.step/secrets/${host}.key"
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare ssh_host=$1
    declare duration=${2:-'9552h'}

    issue-certificate "$ssh_host" "$duration"
    install-certificate "$ssh_host"
fi
