#!/usr/bin/env bash
#
# @(#) bootstrap-smallstep
#
# SYNOPSIS
#     bootstrap-smallstep [user]
#
# DESCRIPTION
#     This script builds Smallstep from source and installs it in
#     /usr/bin. Golang is temporarily installed via the asdf version
#     manager as needed.
#
: ${CHMOD_CMD:='/bin/chmod'}
: ${CAT_CMD:='/bin/cat'}
: ${GIT_CMD:='/usr/bin/git'}
: ${GREP_CMD:='/bin/grep'}
: ${READLINK_CMD:='/bin/readlink'}
: ${RM_CMD:='/bin/rm'}
: ${SUDO_CMD:='/usr/bin/sudo'}

 : ${LOCK:=''}

initialize-asdf-env ()
{
    unset -f asdf

    if test -f "${HOME}/.tool-versions"; then
        $MV_CMD "${HOME}/.tool-versions" "${HOME}/.tool-versions.old" || return $?
    fi

    if test ! -f ~/.bashrc || ! $GREP_CMD -q ASDF_DATA_DIR ~/.bashrc; then
        echo "Appending to bashrc..." >&2

        $CAT_CMD >>~/.bashrc <<'EOF'
# Initialize asdf version manager.
: ${ASDF_DATA_DIR:="${HOME}/.asdf"}

unset -f asdf

if test -d "${ASDF_DATA_DIR}/shims"; then
    export PATH=${ASDF_DATA_DIR}/shims:$PATH
fi

if command -v asdf >/dev/null; then
    source <(asdf completion bash)
fi
EOF
    fi

    export ASDF_DATA_DIR=${HOME}/.asdf
    export PATH=${ASDF_DATA_DIR}/shims:$PATH
}

golang-locally-installed ()
{
    if asdf plugin list | $GREP_CMD -q golang; then
        asdf plugin update golang &>/dev/null || return $?
        if asdf which go &>/dev/null; then
            echo true
        else
            echo false
        fi
    else
        asdf plugin add golang &>/dev/null || return $?
        echo false
    fi
}

install-golang ()
{
    echo "Installing golang..."

    local latest=''

    latest=$(asdf latest golang) || return $?
    asdf install golang "$latest" || return $?
    (cd ~ && asdf set golang "$latest") || return $?
    asdf reshim golang || return $?

    GOPATH=$(go env GOPATH) || return $?
    export GOPATH
}

remove-golang ()
{
    echo "Removing golang..."
    $CHMOD_CMD -R +w "${GOPATH}/../../"
    asdf plugin remove golang
    $RM_CMD -rf "${GOPATH}/../../" ~/.cache/go-build
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=''
    declare script_dir=''

    script=$($READLINK_CMD -e $0) || exit $?
    script_dir=${script%/*}

    declare user=${1:-$USER}

    # Run script as given user.
    if test ."$LOCKED" != ."$script"; then
        exec env LOCKED="$script" $SUDO_CMD -i -u "$user" \
             --preserve-env=LOCKED "$script" "$@"
    fi

    ${script_dir}/install-asdf || exit $?
    initialize-asdf-env || exit $?

    declare have_golang=''

    have_golang=$(golang-locally-installed) || exit $?

    if ! $have_golang; then
        install-golang || exit $?
    fi

    ${script_dir}/install-smallstep || exit $?

    if ! $have_golang; then
        remove-golang || exit $?
    fi
fi
