#!/usr/bin/env bash
#
# @(#) install-smallstep
#
# This script installs current versions of Smallstep CLI and CA.
#
# NB: On systems that must build SmallStep from source (e.g., armv7l),
#     see script bootstrap-smallstep.
#
: ${APT_CMD:='/usr/bin/apt'}
: ${BASH_CMD:='/bin/bash'}
: ${DNF_CMD:='/usr/bin/dnf'}
: ${GETENT_CMD:='/usr/bin/getent'}
: ${GIT_CMD:='/usr/bin/git'}
: ${GO_CMD:="${HOME}/.asdf/shims/go"}
: ${GROUPADD_CMD:='/usr/sbin/groupadd'}
: ${INSTALL_CMD:='/usr/bin/install'}
: ${READLINK_CMD:='/bin/readlink'}
: ${SYSTEMCTL_CMD:='/bin/systemctl'}
: ${SUDO_CMD:='/usr/bin/sudo'}
: ${TEE_CMD:='/usr/bin/tee'}
: ${USERADD_CMD:='/usr/sbin/useradd'}

# OS-agnstoic readlink for existent files/directories.
resolve-existing ()
{
    case $($READLINK_CMD --version 2>&1) in
        *coreutils*)
            $READLINK_CMD -e "$@"
            ;;
        *)
            $READLINK_CMD -f "$@"
            ;;
    esac
}

install-smallstep-infrastructure ()
{
    if ! $GETENT_CMD passwd step >/dev/null; then
        $SUDO_CMD $GROUPADD_CMD -r step || true
        $SUDO_CMD $USERADD_CMD -rm -g step -s "$BASH_CMD" -c 'Smallstep PKI' step || return $?
    fi

    if test -d /usr/lib/tmpfiles.d \
            -a ! -f /usr/lib/tmpfiles.d/step-ca.conf; then
        $SUDO_CMD $TEE_CMD /usr/lib/tmpfiles.d/step-ca.conf >/dev/null <<EOF
d /var/log/step 770 step step
EOF
    fi

    if test -d  /usr/lib/systemd/system \
            -a ! -f /usr/lib/systemd/system/step-ca.service; then
        $SUDO_CMD $TEE_CMD /usr/lib/systemd/system/step-ca.service >/dev/null <<'EOF'
[Unit]
Description=Root Certificate Authority
After=network.target

[Service]
Type=simple
User=step
Group=step
ExecStart=/bin/bash -c "/usr/bin/step-ca '$(/usr/bin/step path)/config/ca.json' --password-file='$(/usr/bin/step path)/secrets/step-ca.pwd'"
ExecReload=/bin/kill --signal HUP $MAINPID
Restart=on-failure
RestartSec=10
TimeoutStopSec=30
StartLimitInterval=30
StartLimitBurst=3

; Process capabilities & privileges
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
SecureBits=keep-caps
NoNewPrivileges=yes

; Sandboxing
; This sandboxing works with YubiKey PIV (via pcscd HTTP API), but it is likely
; too restrictive for PKCS#11 HSMs.
;
; NOTE: Comment out the rest of this section for troubleshooting.
; ProtectSystem=full
; ProtectHome=true
; RestrictNamespaces=true
; RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
; PrivateTmp=true
; ProtectClock=true
; ProtectControlGroups=true
; ProtectKernelTunables=true
; ProtectKernelLogs=true
; ProtectKernelModules=true
; LockPersonality=true
; RestrictSUIDSGID=true
; RemoveIPC=true
; RestrictRealtime=true
; PrivateDevices=true
; SystemCallFilter=@system-service
; SystemCallArchitectures=native
; MemoryDenyWriteExecute=true
; ReadWriteDirectories=/etc/step-ca/db

[Install]
WantedBy=multi-user.target
EOF
    fi
}

install-prerequisites ()
{
    if test -f /etc/os-release; then
        source /etc/os-release
    elif test -f /etc/asl.conf; then
        ID=darwin
    else
        ID=windows
    fi

    case "$ID" in
        ubuntu|debian)
            $SUDO_CMD $APT_CMD update || return $?
            $SUDO_CMD $APT_CMD install -y pkgconf libudev{1,-dev} libusb-1.0-0{,-dev} \
                      libpcsclite{1,-dev} || return $?
            ;;
        darwin|windows)
            if ! pcscd --version &> /dev/null; then
                echo "${script_name}: Don't know how to install PC/SC Lite library." >&2
                return 1
            fi
            ;;
        fedora*|rhel*|rocky*|almalinux*)
            $SUDO_CMD $DNF_CMD install -y pkgconf libusb1{,-devel} pcsc-lite-{devel,libs} \
                      --refresh || retun $?
            ;;
    esac
}

build-smallstep ()
{
    local -n params=$1
    local repo=$2
    local srcdir=$3

    echo "Building and installing SmallStep ${repo^^}..." >&2

    if test -d "$srcdir"; then
        $GIT_CMD -C "$srcdir" pull --rebase
    else
        $INSTALL_CMD -d -m 0700 "$srcdir" || return $?
        $GIT_CMD clone --single-branch --filter=tree:0 \
                 "https://github.com/smallstep/${repo}" "$srcdir" || return $?
    fi

    $GO_CMD -C "${srcdir}/cmd/${params[$repo]}" build -ldflags='-s -w' || return $?
}

install-smallstep ()
{
    local -n params=$1
    local repo=$2
    local srcdir=$3

    $SUDO_CMD $INSTALL_CMD -m 0755 "${srcdir}/cmd/${params[$repo]}/${params[$repo]}" \
              "${params[destdir]}" || return $?
}

maybe-reshim-golang ()
{
    if ! command -v asdf >/dev/null; then
        return 0
    fi

    asdf reshim golang
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    set -e -o pipefail
    shopt -s lastpipe

    declare destdir=${1:-'/usr/bin'}

    declare script=''

    script=$(resolve-existing "$0") || exit $?

    declare script_name=${script##*/}

    if ! command -v $GO_CMD >/dev/null; then
        echo "$script_name: $GO_CMD: No such file or directory" >&2
        exit 1
    fi

    export GOMODCACHE=$($GO_CMD env GOMODCACHE) \
           GOPATH=$($GO_CMD env GOPATH)

    declare -A parameters=(
        [cli]=step
        [certificates]=step-ca
        [destdir]=$destdir
    )

    install-smallstep-infrastructure || exit $?

    if command -v "$SYSTEMCTL_CMD" >/dev/null \
            && $SYSTEMCTL_CMD is-enabled step-ca &>/dev/null; then
        $SUDO_CMD $SYSTEMCTL_CMD stop step-ca
    fi

    if test -f /etc/os-release; then
        source /etc/os-release

        case "$ID" in
            fedora*)
                if ! command -v dnf5 >/dev/null; then
                    $DNF_CMD install -y dnf5{,-plugins}
                fi
                export DNF_CMD=/usr/bin/dnf5
                ;;
        esac
    fi

    install-prerequisites || exit $?

    declare srcdir=''
    declare repo=''

    for repo in cli certificates; do
        srcdir=${GOMODCACHE}/github.com/smallstep/${repo}
        build-smallstep parameters "$repo" "$srcdir" || exit $?
        install-smallstep parameters "$repo" "$srcdir" || exit $?
    done
    maybe-reshim-golang "${GO_CMD%/*}" || exit $?

    if command -v "$SYSTEMCTL_CMD" >/dev/null \
               && test -f /usr/lib/systemd/system/step-ca.service; then
        $SUDO_CMD $SYSTEMCTL_CMD start step-ca || return $?
    fi
fi
