#!/usr/bin/env bash
#
# @(#) flash-emmc
#
# Copyright © 2021,2024 Revolution Robotics, Inc.
#
# This script creates a bootable eMMC device with Debian root
# and recovery filesystems. It must be run from a non-eMMC root
# partition.
#
: ${COMPRESSION_SUFFIX:=zst}
: ${ZCAT_CMD:='/usr/bin/zstdmt -cd'}
: ${IMAGES_PATH:=/opt/images/Debian}
: ${PAYLOADS_PATH:=/opt/images/payloads}
: ${EMMC_DEVICE:=mmcblk2}
: ${UBOOT_IMAGE:=u-boot.img.mmc}
: ${UBOOT_SCRIPT:=boot.scr}
: ${SPL_IMAGE:=SPL.mmc}
: ${KERNEL_IMAGE:=uImage}
: ${KERNEL_DTBS:='imx7d-roadrunner-blade.dtb imx7d-roadrunner-gpio16.dtb imx7d-roadrunner-iomix.dtb'}
: ${ROOTFS_IMAGE:="rootfs.tar.${COMPRESSION_SUFFIX}"}
: ${RECOVERYFS_IMAGE:="recoveryfs.tar.${COMPRESSION_SUFFIX}"}
: ${SYSTEM_UPDATE_LOG:=/root/system-update.log}

usage ()
{
    cat <<EOF
Usage: $script_name OPTIONS
Options:
  -h|--help              -- print this help, then exit.
EOF
}

pr-error ()
{
    echo "E: $@"
}

pr-info ()
{
    echo "I: $@"
}

pwr-led-on ()
{
    echo 1 >/sys/class/leds/pwr-green-led/brightness
}

pwr-led-off ()
{
    echo 0 >/sys/class/leds/pwr-green-led/brightness
}

stat-led-on ()
{
    echo 1 >/sys/class/leds/stat-blue-led/brightness
}

stat-led-off ()
{
    echo 0 >/sys/class/leds/stat-blue-led/brightness
}

link-led-on ()
{
    echo 1 >/sys/class/leds/link-blue-led/brightness
}

link-led-off ()
{
    echo 0 >/sys/class/leds/link-blue-led/brightness
}

cycle-leds ()
{
    while true; do
        pwr-led-on
        sleep 1
        pwr-led-off
        stat-led-on
        sleep 1
        stat-led-off
        link-led-on
        sleep 1
        link-led-off
    done
}

# Check that none of the partitions to be flashed is mounted as root.
sanity-check ()
{
    local device=$1
    local part=$2
    local rootfspart=$3
    local recoveryfspart=$4

    local system_update=$(readlink /system-update)
    local rootdevice=${device}${part}${rootfspart}
    local rootmount=$(findmnt -n "$rootdevice" | awk '{ print $1 }')
    local recoverydevice=${device}${part}${recoveryfspart}
    local recoverymount=$(findmnt -n "$recoverydevice" | awk '{ print $1 }')

    if test ."$rootmount" = .'/'; then
        pr-error "$rootdevice: Cannot flash device mounted on root"
        return 1
    elif test ."$recoverymount" = .'/'; then
        pr-error "$recoverydevice: Cannot flash device mounted on root"
        return 1
    fi

    if ! $interactive; then
        if test ."$system_update" != .'opt/images/Debian'; then
            pr-error "/system-update: Not symlinked to opt/images/Debian"
            return 1
        else

            # Per systemd.offline-update(7) documentation, the symlink
            # `/system-update' must exist prior to an offline update and
            # removed early in the update process to prevent a reboot
            # cycle in the event of a failure.
            #
            # But if recovery is initiated from U-Boot (e.g., if rootfs is
            # not bootable), U-Boot is presently unable to create symlinks
            # on ext4 file systems. So to support this case, the
            # `/system-update' symlink should never be removed from the
            # recovery file system.
            : rm -f /system-update
        fi
    fi
}

check-images ()
{
    local dtb
    local image
    local -a distribution_images=(
        "$UBOOT_IMAGE"
        "$UBOOT_SCRIPT"
        "$SPL_IMAGE"
        "$KERNEL_IMAGE"
        "$ROOTFS_IMAGE"
        "$RECOVERYFS_IMAGE"
        )

    for dtb in $KERNEL_DTBS; do
        if test ! -f "${IMAGES_PATH}/${dtb}"; then
            pr-error "${IMAGES_PATH}/${dtb}: No such file"
            return 1
        fi
    done

    for image in "${distribution_images[@]}"; do
        if test ! -f "${IMAGES_PATH}/${image}"; then
            pr-error "${IMAGES_PATH}/${image}: No such file"
            return 1
        fi
    done
}

# $1 is the full path of the config file
set-fw-env-config-to-emmc ()
{
    local fw_env_config=$1

    sed -i -e '/mtd/ s/^#*/#/' "$fw_env_config"
    sed -i -e "s;#*/dev/mmcblk.;/dev/${EMMC_DEVICE};" "$fw_env_config"
}

set-fw-utils-to-emmc-on-sd-card ()
{
    local fw_printenv=$(readlink /usr/bin/fw_printenv)

    # Adjust u-boot-fw-utils for eMMC on the SD card
    if test ."$fw_printenv"  != ."fw_printenv-mmc"; then
        ln -sf fw_printenv-mmc /usr/bin/fw_printenv
    fi

    if test -f /etc/fw_env.config; then
        set-fw-env-config-to-emmc /etc/fw_env.config
    fi
}

set-fw-utils-to-emmc-on-emmc ()
{
    local mountpoint=$1

    # Adjust u-boot-fw-utils for eMMC on the installed rootfs
    if test -f "${mountpoint}/usr/bin/fw_printenv-mmc"; then
        mv "${mountpoint}/usr/bin/fw_printenv-mmc" \
           "${mountpoint}/usr/bin/fw_printenv"
    fi

    if test -f "${mountpoint}/etc/fw_env.config"; then
        set-fw-env-config-to-emmc "${mountpoint}/etc/fw_env.config"
    fi
}

partition-emmc ()
{
    local device=$1
    local part=$2

    # Sizes in MiB
    # RECOVERYFS_SIZE must match that in recover-emmc.
    # local RECOVERYFS_SIZE=1792
    local RECOVERYFS_SIZE=2300
    local BOOTLOAD_RESERVE_SIZE=4
    local SPARE_SIZE=12

    # Get total device size in blocks
    local total_size=$(blockdev --getsz "$device")
    local total_size_bytes=$(( total_size * 512 ))
    local total_size_gib=$(perl -e "printf '%.1f', $total_size_bytes / 2 ** 30")

    # Convert to MiB
    total_size=$(( total_size / 2048 ))
    local rootfs_offset=$(( BOOTLOAD_RESERVE_SIZE + SPARE_SIZE ))
    local rootfs_size=$(( total_size - rootfs_offset - RECOVERYFS_SIZE ))
    local recoveryfs_offset=$(( rootfs_offset + rootfs_size ))

    pr-info "Device: $device, $total_size_gib GiB"
    pr-info '============================================='
    if $interactive; then
        read -p 'Press Enter to continue'
    fi

    pr-info 'Creating new partitions:'
    pr-info "Root file system size: $rootfs_size MiB"
    pr-info "Recovery file system size: $RECOVERYFS_SIZE MiB"
    pr-info "Total size: $total_size MiB"

    local part1_start="${BOOTLOAD_RESERVE_SIZE}MiB"
    local part1_size="${SPARE_SIZE}MiB"
    local part2_start="${rootfs_offset}MiB"
    local part2_size="${rootfs_size}MiB"
    local part3_start="${recoveryfs_offset}MiB"

    # Erase file system signatures and labels
    for (( i=0; i < 10; i++ )); do
        if test -n "$(findmnt -n "${device}${part}${i}")"; then
            umount "${device}${part}${i}"
        fi
        if test -e "${device}${part}${i}"; then
            tune2fs -L '' "${device}${part}${i}" >/dev/null 2>&1
            wipefs -a "${device}${part}${i}" >/dev/null 2>&1
        fi
    done
    wipefs -a "$device" >/dev/null 2>&1

    dd if=/dev/zero of="$device" bs=1M count="$rootfs_offset" >/dev/null 2>&1
    sleep 2
    sync

    flock "$device" sfdisk "$device" >/dev/null 2>&1 <<EOF
$part1_start,$part1_size,c
$part2_start,$part2_size,L
$part3_start,-,L
EOF

    partprobe "$device"
    sleep 2
    sync
}

format-emmc ()
{
    local device=$1
    local part=$2
    local bootpart=$3
    local rootfspart=$4
    local recoveryfspart=$5

    pr-info 'Formating eMMC partitions'

    if ! mkfs.vfat -n BOOT "${device}${part}${bootpart}" >/dev/null 2>&1; then
        pr-error "${device}${part}${bootpart}: format failed"
        return 1
    elif ! mkfs.ext4 -F -L rootfs "${device}${part}${rootfspart}" >/dev/null 2>&1; then
        pr-error "${device}${part}${rootfspart}: format failed"
        return 1
    elif ! mkfs.ext4 -F -L recoveryfs "${device}${part}${recoveryfspart}" >/dev/null 2>&1; then
        pr-error "${device}${part}${recoveryfspart}: format failed"
        return 1
    fi
    sleep 2
    sync
}

mount-partitions ()
{
    local mountdir_prefix=$1
    local device=$2
    local part=$3
    local bootpart=$4
    local rootfspart=$5
    local recoveryfspart=$6

    local bootdir="${mountdir_prefix}${bootpart}"
    local rootfsdir="${mountdir_prefix}${rootfspart}"
    local recoveryfsdir="${mountdir_prefix}${recoveryfspart}"

    pr-info 'Mounting eMMC partitions'

    # Mount the partitions
    mkdir -p "$bootdir"
    mkdir -p "$rootfsdir"
    mkdir -p "$recoveryfsdir"

    if ! mount -t vfat "${device}${part}${bootpart}" "$bootdir" >/dev/null 2>&1; then
        pr-error "${device}${part}${bootpart}: mount failed"
        return 1
    elif ! mount -t ext4 "${device}${part}${rootfspart}" "$rootfsdir" >/dev/null 2>&1; then
        pr-error "${device}${part}${rootfspart}: mount failed"
        return 1
    elif ! mount -t ext4 "${device}${part}${recoveryfspart}" "$recoveryfsdir" >/dev/null 2>&1; then
        pr-error "${device}${part}${recoveryfspart}: mount failed"
        return 1
    fi
    sleep 2
    sync
}

flash-emmc-partitions ()
{
    local mountdir_prefix=$1
    local bootpart=$2
    local rootfspart=$3
    local recoveryfspart=$4

    local bootdir="${mountdir_prefix}${bootpart}"
    local rootfsdir="${mountdir_prefix}${rootfspart}"
    local recoveryfsdir="${mountdir_prefix}${recoveryfspart}"

    pr-info 'Flashing eMMC "BOOT" partition'

    if test -f "${IMAGES_PATH}/${UBOOT_SCRIPT}"; then
        install -m 0644 "${IMAGES_PATH}/${UBOOT_SCRIPT}" "$bootdir"
    fi
    cp "${IMAGES_PATH}/${KERNEL_IMAGE}" "$bootdir"
    for dtb in $KERNEL_DTBS; do
        cp "${IMAGES_PATH}/${dtb}" "$bootdir"
    done
    sync

    pr-info 'Flashing eMMC "rootfs" partition'

    if ! $ZCAT_CMD "${IMAGES_PATH}/${ROOTFS_IMAGE}" |
            tar -C "$rootfsdir" -xpf - \
                --checkpoint=4096 --checkpoint-action=.; then
        pr-error "$rootfsdir: eMMC flash failed."
        return 1
    fi
    pr-info ''

    set-fw-utils-to-emmc-on-emmc "$rootfsdir"
    sync

    pr-info 'Flashing eMMC "recoveryfs" partition'

    if ! $ZCAT_CMD "${IMAGES_PATH}/${RECOVERYFS_IMAGE}" |
            tar -C "$recoveryfsdir" -xpf - \
                --checkpoint=4096 --checkpoint-action=.; then
        pr-error "$recoveryfsdir: eMMC flash failed."
        return 1
    fi
    install -m 0644 /etc/hosts "${recoveryfsdir}/etc"
    pr-info ''

    set-fw-utils-to-emmc-on-emmc "$recoveryfsdir"
    sync
}

deploy-payloads ()
{
    local rootfsdir=$1

    pr-info 'Deploying paylods to "rootfs" partition'

    find "$PAYLOADS_PATH" -type f -name "*.${COMPRESSION_SUFFIX}" 2>/dev/null |
        while read payload; do
            if ! $ZCAT_CMD "$payload" |
                    tar -C "$rootfsdir" -xpf -; then
                pr-error "${rootfsdir}: Payload deployment failed."
                return 1
            fi
        done
}

run-post-install ()
{
    local script=$1
    local rootfsdir=$2

    if test ! -f "$script"; then
        return
    fi

    trap 'rm -f "${rootfsdir}/post-install"; exit 1' 0 1 2 15 RETURN

    install -m 0644 /etc/hosts "${rootfsdir}/etc" || return $?
    install -m 0755 "$script" "${rootfsdir}/post-install" || return $?
    chrootfs "${rootfsdir}" /post-install || return $?
    rm -f "${rootfsdir}/post-install" || return $?

    trap - 0 1 2 15 RETURN
}

copy-images ()
{
    local recoveryfsdir=$1

    local dtb
    local image
    local recovery_images_path=${recoveryfsdir}${IMAGES_PATH}
    local -a recovery_images=(
        "$UBOOT_IMAGE"
        "$UBOOT_SCRIPT"
        "$SPL_IMAGE"
        "$KERNEL_IMAGE"
        "$ROOTFS_IMAGE"
        )

    pr-info "Installing recovery images"

    install -d -m 0750 -p "$recovery_images_path"
    for dtb in $KERNEL_DTBS; do
        install -m 0644 "${IMAGES_PATH}/${dtb}" "$recovery_images_path"
    done

    for image in "${recovery_images[@]}"; do
        install -m 0644 "${IMAGES_PATH}/${image}" "$recovery_images_path"
    done

    tar -C / -cf - "${PAYLOADS_PATH#/}" | tar -C "$recoveryfsdir" -xpf -
}

flash-uboot ()
{
    local device=$1

    local spl_image=${IMAGES_PATH}/${SPL_IMAGE}
    local uboot_image=${IMAGES_PATH}/${UBOOT_IMAGE}

    pr-info "Flashing eMMC U-Boot"

    if ! dd if="$spl_image" of="$device" bs=1K seek=1 >/dev/null 2>&1; then
        pr-error "eMMC flash failed."
        return 1
    fi
    sync
    if ! dd if="$uboot_image" of="$device" bs=1K seek=69 >/dev/null 2>&1; then
        pr-error 'eMMC flash failed.'
        return 1
    fi
    sync
    sleep 2
}

clean-up ()
{

    local mountdir_prefix=$1
    local bootpart=$2
    local rootfspart=$3
    local recoveryfspart=$4

    local bootdir="${mountdir_prefix}${bootpart}"
    local rootfsdir="${mountdir_prefix}${rootfspart}"
    local recoveryfsdir="${mountdir_prefix}${recoveryfspart}"

    umount "$bootdir" "$rootfsdir" "$recoveryfsdir" || return 1

    if [[ ."${mountdir_prefix%/*}" =~ \./tmp/media ]]; then
        rm -rf "${mountdir_prefix%/*}"
    fi

    pr-info "eMMC flash completed successfully"
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script=''
    declare script_name=''

    script=$(readlink -e "$0") || exit $?
    script_name=${script##*/}

    declare interactive=true

    while getopts hq c;
    do
        case $c in
            h|\?)
                usage
                exit 1
                ;;
            q)
                interactive=false

                # Log all stdout and stderr to SYSTEM_UPDATE_LOG
                exec >"$SYSTEM_UPDATE_LOG" 2>&1
                ;;
        esac
        shift
    done

    if (( EUID != 0 )); then
        echo "This script must be run with super-user privileges"
        exit 1
    fi

    declare soc=$(< /sys/bus/soc/devices/soc0/soc_id)
    declare device=/dev/${EMMC_DEVICE}
    declare part=p
    declare mountdir_prefix=/tmp/media/${EMMC_DEVICE}${part}
    declare bootpart=1
    declare rootfspart=2
    declare recoveryfspart=3
    declare post_install_script=${PAYLOADS_PATH}/post-install

    if test ."$soc" != .'i.MX7D'; then
        pr-error "This script is for imaging an i.MX7D board's eMMC device"
        exit 1
    elif test ! -b $device; then
        pr-error "$device: Device not found"
        exit 1
    fi

    pr-info "Board: $soc"
    pr-info "Internal storage: eMMC"

    sanity-check "$device" "$part" "$rootfspart" "$recoveryfspart" || exit $?
    check-images || exit $?

    if ! $interactive; then
        declare cycle_leds_pid=''

        cycle-leds &
        cycle_leds_pid=$!
    fi

    partition-emmc "$device" "$part" || exit $?
    format-emmc "$device" "$part" "$bootpart" "$rootfspart" \
                "$recoveryfspart" || exit $?
    mount-partitions "$mountdir_prefix" "$device" "$part" "$bootpart" \
                     "$rootfspart" "$recoveryfspart" || exit $?
    flash-emmc-partitions "$mountdir_prefix" "$bootpart" "$rootfspart" \
                          "$recoveryfspart" || exit $?
    deploy-payloads "${mountdir_prefix}${rootfspart}" || exit $?
    run-post-install "$post_install_script" \
                     "${mountdir_prefix}${rootfspart}" || exit $?
    copy-images "${mountdir_prefix}${recoveryfspart}"
    flash-uboot "$device" || exit $?
    clean-up "$mountdir_prefix" "$bootpart" "$rootfspart" \
             "$recoveryfspart" || exit $?

    # Per /BOOT/boot.scr, setting `usbboot_request' to `override' forces
    # boot to eMMC prior to restoring USB boot.
    set-fw-utils-to-emmc-on-sd-card
    fw_setenv usbboot_request override

    if ! $interactive; then
        pwr-led-on
        stat-led-off
        link-led-off
        kill "$cycle_leds_pid"
    fi
fi
