#!/usr/bin/env bash
#
# @(#) update-kernel-cmdline
#
# Copyright © 2021 Revolution Robotics, Inc.
#
# This script updates the kernel command-line from the contents of
# /boot/cmdline.txt.
#
: ${AWK_CMD:='/usr/bin/awk'}
: ${ED_CMD:='/bin/ed'}
: ${FINDMNT_CMD:='/bin/findmnt'}
: ${FLOCK_CMD:='/usr/bin/flock'}
: ${INSTALL_CMD:='/usr/bin/install'}
: ${MAKE_CMD:='/usr/bin/make'}
: ${MKIMAGE_CMD:='/usr/bin/mkimage'}
: ${MKTEMP_CMD:='/usr/bin/mktemp'}
: ${MOUNT_CMD:='/bin/mount'}
: ${RM_CMD:='/bin/rm'}
: ${SUDO_CMD:='/usr/bin/sudo'}
: ${SYSTEMCTL_CMD:='/bin/systemctl'}
: ${UMOUNT_CMD:='/bin/umount'}

: ${LOCKED_CMD:=''}

process-cmdline ()
{
    local mountdir=$1
    local tmpdir=$2

    local cmdline=$($ED_CMD -Ee '/^\s*[[:alnum:]]/s;^\s*;;p' "/boot/cmdline.txt")

    $INSTALL_CMD -m 0644 /usr/share/boot/boot.sh "${tmpdir}"
    $ED_CMD -i -e "/^setenv kernelargs/s;\$; ${cmdline};" "${tmpdir}/boot.sh"
    $MAKE_CMD -C "$tmpdir" -f "/usr/share/boot/Makefile"

    if test -f "${tmpdir}/boot.scr"; then
        local boot_device=$(
            $FINDMNT_CMD -n / |
                $AWK_CMD '{ sub(/p[0-9]$/, "p1", $2); print $2 }'
                )
        $MOUNT_CMD "$boot_device" "$mountdir"
        $SUDO_CMD $INSTALL_CMD -m 0644 "${tmpdir}/boot.scr" "$mountdir"

        case $cmdline in
            *selinux*)
                $SYSTEMCTL_CMD unmask selinux.service
                $SYSTEMCTL_CMD enable selinux.service
                $SYSTEMCTL_CMD disable apparmor.service
                $SYSTEMCTL_CMD mask apparmor.service
                ;;
            *apparmor*)
                $SYSTEMCTL_CMD unmask apparmor.service
                $SYSTEMCTL_CMD enable apparmor.service
                $SYSTEMCTL_CMD disable selinux.service
                $SYSTEMCTL_CMD mask selinux.service
                ;;
        esac
    fi
}

clean-up ()
{
    local mountdir=$1
    local tmpdir=$2

    if $FINDMNT_CMD -n "$mountdir" >/dev/null; then
       $UMOUNT_CMD -f "$mountdir"
    fi
    if test -d "$tmpdir"; then
        $RM_CMD -rf "$tmpdir"
    fi
    $SYSTEMCTL_CMD daemon-reload
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare script_name=${0##*/}

    if test -x "$FLOCK_CMD" -a ."$0" != ."$LOCKED_CMD"; then

        #  Avoid running multiple instances of this script.
        exec env LOCKED_CMD=$0 $FLOCK_CMD -en "$0" "$0" "$@" || true
    fi

    declare mountdir=/mnt
    declare tmpdir=$($MKTEMP_CMD -p '' -d "${script_name}.XXXXXXX")

    trap 'clean-up "$mountdir" "$tmpdir"; exit' 0  1 2 15

    process-cmdline "$mountdir" "$tmpdir"
fi
