#!/usr/bin/env bash
#
# Copyright © 2021 Revolution Robotics, Inc.
#
# @(#) update-hostname
#
# This script attempts to update the system hostname across various
# files/certs. The system should be immediately rebooted thereafter to
# eliminate transients. Assumptions are made that won't be valid on
# most systems.
#
# In general, changing the system hostname is a bad idea, so use this
# script only as a last resort!
#
: ${AWK_CMD:='/usr/bin/awk'}
: ${CUT_CMD:='/usr/bin/cut'}
: ${FLOCK_CMD:='/usr/bin/flock'}
: ${GREP_CMD:='/bin/grep'}
: ${HOSTNAMECTL_CMD:='/usr/bin/hostnamectl'}
: ${IP_CMD:='/bin/ip'}
: ${OPENSSL_CMD:='/usr/bin/openssl'}
: ${RM_CMD:='/bin/rm'}
: ${SED_CMD:='/bin/sed'}
: ${SSH_KEYGEN_CMD:='/usr/bin/ssh-keygen'}
: ${TLS_GENERATE_SELF_SIGNED_CMD:='/usr/sbin/tls-generate-self-signed'}
: ${SYSTEMCTL_CMD:='/bin/systemctl'}

: ${LOCKED:=''}

confirm-update ()
{
    local msg=$1

    echo "$msg"
    read -n 1 -p "Continue? [y/N]? "
    echo
    if [[ ."$REPLY" = .'' || ."$REPLY" == .[nN] ]]; then
        return 1
    fi
}

get-mac-digest ()
{
    $IP_CMD -o -br link show |
        $GREP_CMD -E '^(e|w)' |
        $AWK_CMD '{ print $3; exit }' |
        $OPENSSL_CMD dgst -r -sha256 |
        $CUT_CMD -c1-6
}

update-hostnames ()
{
    local hn=$1

    $HOSTNAMECTL_CMD --static --transient --pretty set-hostname "$hn"
}

update-hosts ()
{
    local hn=$1

    $SED_CMD -i -E -e 's;^(127.0.0.1).*;\1\tlocalhost;' \
        -e "s;^(127.0.1.1).*;\1\t$hn;" /etc/hosts
}

update-mailname ()
{
    local hn=$1

    echo "$hn" >/etc/mailname
}

update-ssh-certificates ()
{
    $RM_CMD -f /etc/ssh/ssh_host_*_key*
    $SSH_KEYGEN_CMD -A
}

update-tls-certificates ()
{
    $TLS_GENERATE_SELF_SIGNED_CMD
}

restart-zeroconf ()
{
    if $SYSTEMCTL_CMD is-active avahi-daemon >/dev/null; then
        $SYSTEMCTL_CMD restart avahi-daemon
    fi
}

restart-web-services ()
{
    if $SYSTEMCTL_CMD is-active cockpit >/dev/null; then
        $SYSTEMCTL_CMD restart cockpit
    fi

    if $SYSTEMCTL_CMD is-active revo-web-dispatch >/dev/null; then
        $SYSTEMCTL_CMD restart revo-web-dispatch
    fi
}

process-command-line ()
{
    local -n new_hostname=$1
    local update=$2

    # Remove any domain part.
    new_hostname=${update%%.*}

    local msg=''

    if test ."$new_hostname" = .''; then
        new_hostname=revoedge-$(get-mac-digest)

        if test ."$new_hostname" = ."$HOSTNAME" -a -f /etc/hostname; then
            if test ."$new_hostname" = .$(< /etc/hostname); then
                msg="$new_hostname: Hostname appears already set."
                confirm-update "$msg" || exit
            fi
        fi
    elif test ."${new_hostname:0:1}" = .'-'; then
        echo "Usage: ${0##*/} [hostname]"
        exit
    elif test ! ."$update" = ."$new_hostname"; then
        msg="NB: Only short name (i.e., $new_hostname) will be updated.
    Domain name records must be updated separately."
        confirm-update "$msg" || exit
    elif test ."$new_hostname" = ."$HOSTNAME" -a -f /etc/hostname; then
        if test ."$new_hostname" = .$(< /etc/hostname); then
            msg="$new_hostname: Hostname appears set already."
            confirm-update "$msg" || exit
        fi
    fi
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then

    if test ."$LOCKED" != ."$0"; then

        #  Avoid running multiple instances of this script.
        exec env LOCKED=$0 $FLOCK_CMD -en "$0" "$0" "$@" || exit 1
    fi

    declare requested_hostname=''

    process-command-line requested_hostname "$@" || exit $?

    cat <<EOF
Updating: $HOSTNAME → $requested_hostname
EOF

    update-hostnames "$requested_hostname" || exit $?
    update-hosts "$requested_hostname" || exit $?
    update-mailname "$requested_hostname" || exit $?

    # NB: Certificates must be regenerated last!
    update-ssh-certificates || exit $?
    update-tls-certificates || exit $?

    restart-zeroconf || exit $?
    restart-web-services || exit $?

    cat <<EOF
Update complete! Adjust DNS records accordingly.
Please reboot the system NOW!
EOF

fi
