#!/usr/bin/env bash
#
# @(#) install-node-lts
#
# This script installs node version manager and then the latest node
# version of the $node_base series.
#

# Edit these ...
: ${NODE_BASE:='@NODE_BASE@'}
: ${NODE_GROUP:='@NODE_GROUP@'}
: ${NODE_USER:='@NODE_USER@'}

# Command paths
: ${AWK:='/usr/bin/awk'}
: ${BASH:='/bin/bash'}
: ${CAT:='/bin/cat'}
: ${CURL:='/usr/bin/curl'}
: ${GETENT:='/usr/bin/getent'}
: ${GIT:='/usr/bin/git'}
: ${GREP:='/bin/grep'}
: ${GROUPADD:='/usr/sbin/groupadd'}
: ${SED:='/bin/sed'}
: ${SORT:='/usr/bin/sort'}
: ${SUDO:='/usr/bin/sudo'}
: ${TAIL:='/usr/bin/tail'}
: ${USERADD:='/usr/sbin/useradd'}

if ! $GETENT passwd "$NODE_USER" >/dev/null 2>&1; then
    $SUDO $GROUPADD "$NODE_GROUP"
    $SUDO $USERADD -m -g "$NODE_GROUP" -s "$BASH" -c "Node User" "$NODE_USER"
fi

declare homedir=$($GETENT passwd "$NODE_USER" | $AWK -F: '{ print $6 }')

clone_asdf_repo ()
{
    echo "Cloning..."
    $CAT <<EOF | $SUDO  -u "$NODE_USER" $BASH -s
git clone https://github.com/asdf-vm/asdf.git ~/.asdf || true
EOF
    echo "Done cloning..."
}

init_asdf_in_bashrc ()
{
    echo "Appending to bashrc..."
    $CAT >>"${homedir}/.bashrc" <<'EOF'

# Initialize asdf version manager.
export ASDF_DIR=~/.asdf
if test -f "${ASDF_DIR}/asdf.sh"; then
    source "${ASDF_DIR}/asdf.sh"
    source "${ASDF_DIR}/completions/asdf.bash"
fi
EOF
}

install_node ()
{
    echo "Installing node..."
    $CAT <<EOF | $SUDO -i -u "$NODE_USER" $BASH -s
export ASDF_DIR=~/.asdf
if test -f "\${ASDF_DIR}/asdf.sh"; then
    . "\${ASDF_DIR}/asdf.sh"
    if type asdf >/dev/null 2>&1; then
        asdf plugin add nodejs
        node_lts=\$(asdf latest nodejs "$NODE_BASE")
        asdf install nodejs "\$node_lts"
        asdf global  nodejs "\$node_lts"
    fi
fi
EOF
}

clone_asdf_repo
init_asdf_in_bashrc
install_node
