#!/usr/bin/env bash
#
# @(#) ip-funcs
#
# Copyright © 2020, Revolution Robotics, Inc.
#
shopt -s extglob

# is-ipv4-addr: Sanity check IPv4 address. Expected format:
#     dotted-quad/netmask, e.g., 192.168.0.1/24
is-ipv4-addr ()
{
    local ipv4_addr=$1

    local quad=${ipv4_addr%/*}
    local mask=${ipv4_addr#*/}

    is-dotted-quad "$quad" &&
        [[ ."$mask" =~ ^\.(0|[1-9]|[12][0-9]|3[0-2])$ ]]
}

# is-dotted-quad: Sanity check given dotted quad,
#     e.g., 255.255.255.0
is-dotted-quad ()
{
    local quad=$1
    local num

    set -- $(IFS=.; echo $quad)

    [ $# -eq 4 ] || return 1
    for num; do
        [[ ."$num" =~ ^\.(0|[1-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]] || return 1
    done
}

# inet-aton: Convert quad-dotted to 32-bit number,
#     e.g., 10.0.0.1 => 167772161
inet-aton ()
{
    local quad=$1

    if ! is-dotted-quad "$quad"; then
        return 127
    fi

    set -- $(IFS=.; echo $quad)

    local -i class_no=0
    local -i ip_no=0

    for class_no; do
        ip_no=$(( ip_no << 8 | class_no ))
    done

    echo "$ip_no"
}

# inet-mask-ntoa: Convert netmask size to dotted-quad,
#     e.g., 24 => 255.255.255.0
inet-mask-ntoa ()
{
    local -i mask=$1

    if (( mask < 0 || mask > 32 )); then
        return 127
    elif (( mask == 0 )); then
        echo '0.0.0.0'
        return
    fi

    inet-ntoa $(( 0xffffffff & (0xffffffff << (32 - mask)) ))
}

# inet-ntoa: Convert 32-bit number to dotted-quad,
#     e.g., 167772161 => 10.0.0.1
inet-ntoa ()
{
    local -i ip_no=$1

    if (( ip_no < 0 || ip_no > 0xffffffff )); then
        return 1
    elif (( ip_no == 0 )); then
        echo '0.0.0.0'
        return
    fi

    local quad=$(( ip_no & 0xff ))

    while (( ip_no >>= 8 )); do
        quad=$(( ip_no & 0xff )).$quad
    done

    echo "$quad"
}

# network-exclusive: Given two IPv4 addresses, return 0 if neither is
#     in the other's network. Expected IPv4 format: dotted-quad/netmask,
#     e.g., 10.0.0.1/24
network-exclusive ()
{
    local ipv4_addr1=$1
    local ipv4_addr2=$2

    if ! is-ipv4-addr "$ipv4_addr1" || ! is-ipv4-addr "$ipv4_addr2"; then
        return 127
    fi

    local quad1=${ipv4_addr1%/*}
    local mask1=${ipv4_addr1##*/}
    local quad2=${ipv4_addr2%/*}
    local mask2=${ipv4_addr2##*/}

    local -i nq1=0
    local qm1=''
    local -i nm1=0

    local -i nq2=0
    local qm2=''
    local -i nm2=0

    nq1=$(inet-aton "$quad1") || return $?
    qm1=$(inet-mask-ntoa "$mask1") || return $?
    nm1=$(inet-aton "$qm1") || return $?

    nq2=$(inet-aton "$quad2") || return $?
    qm2=$(inet-mask-ntoa "$mask2") || return $?
    nm2=$(inet-aton "$qm2") || return $?

    # addr2 in network1 and addr1 in network2
    if (( (nq1 & nm1) == (nq2 & nm1) )) && (( (nq1 & nm2) == (nq2 & nm2) )); then
        return 3
    # addr2 in network1
    elif (( (nq1 & nm1) == (nq2 & nm1) )); then
        return 2
    # addr1 in network2
    elif (( (nq1 & nm2) == (nq2 & nm2) )); then
        return 1
    fi
}
