#!/usr/bin/env bash
#
# @(#) wifi-gateway
#
# Copyright © 2020, Revolution Robotics, Inc.
#
# This script creates and activates a NetworkManger WiFi gateway profile.
#
script_name=${0##*/}
script_dir=${0%/*}

: ${CAT:='/bin/cat'}

source "${script_dir}/ip-funcs"
source "${script_dir}/nm-funcs"

declare -A param=(
    [mode]=gw
    [interface]=$(get-managed-interfaces wifi | head -1)
)

usage ()
{
    $CAT <<EOF
Usage: $script_name -p PROFILE -i INTERFACE -s SSID -p PASSWORD OPTIONS
where OPTIONS are:
  -h|--help      Display help, then exit
  -p|--profile=PROFILE
                 Set connection profile name to PROFILE (e.g., ${param[interface]}-gw)
  -i|--interface=INTERFACE
                 Set network interface to INTERFACE (default: ${param[interface]})
  -s|--ssid      Set WiFi network name to SSID
  -P|--password=PASSWORD
                 Set WiFi network password to PASSWORD
  -a|--address=IPv4_ADDR
                 Set IPv4 address/netmask of interface to IPv4_ADDR (optional)
                 (e.g., 10.100.0.25/24)
  -g|--gateway=IPv4_GATEWAY
                 Set IPv4 address of gateway to IPv4_GATEWAY (optional)
                 (e.g., 10.100.0.1)
  -o|--priority=PRIORITY
                 Set connection priority to PRIORITY
  -r|--retries=RETRIES
                 Set connection retries to RETRIES
EOF
}

declare opts
declare status
declare -r short_opts=a:,g:,h,i:,o:,P:,p:,r:,s:
declare -r long_opts=address:,gateway:,help,interface:,password:,priority:,profile:,retries:,ssid:

opts=$(
    getopt --name "$script_name" --options "$short_opts"  \
           --longoptions "$long_opts" -- "$@"
    )

status=$?
if (( status != 0 )); then
    exit $status
fi

eval set -- "$opts"

while true; do
    case "$1" in
        -a|--address)
            param[ipv4_addr]=$2
            ;;
        -g|--gateway)
            param[ipv4_gateway]=$2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -i|--interface)
            param[interface]=$2
            ;;
        -o|--priority)
            param[priority]=$2
            ;;
        -P|--password)
            param[password]=$2
            ;;
        -p|--profile)
            param[profile]=$2
            ;;
        -r|--retries)
            param[retries]=$2
            ;;
        -s|--ssid)
            param[ssid]=$2
            ;;
        --)
            break
            ;;
    esac
    shift 2
done

if test ."${param[profile]}" = .''; then
    echo "$script_name: $param[profile]: Not a valid profile name" >&2
    exit 1
fi

validate-interface "${param[interface]}" || exit $?

if test ."${param[ipv4_addr]}" != .''; then
    validate-ipv4-address "${param[ipv4_addr]}" || exit $?
fi

if test ."${param[ipv4_gateway]}" != .''; then
    validate-ipv4-gateway "${param[ipv4_gateway]}" || exit $?
fi

disconnect-interface "${param[interface]}"
remove-previous-profile "${param[profile]}"
create-wifi-profile 'param'
activate-profile "${param[profile]}" 'toggle'
