#!/usr/bin/env bash
#
# @(#) 50-default-wifi-ap
#
# Copyright © 2020, Revolution Robotics, Inc.
#
: ${AWK:='/bin/awk'}
: ${NMCLI:='/bin/nmcli'}
: ${SED:='/bin/sed'}
: ${TR:='/bin/tr'}

declare interface=$1
declare status=$2

declare -r LOCKDIR=/var/run/NetworkManager/defaul-wifi-ap-lock
declare -r ACCESS_POINT=/usr/lib/NetworkManager/access-point.sh

declare -a wifi_interfaces
declare wifi_interface
declare profile

source "/usr/lib/NetworkManager/nm-funcs.sh"

# Use $LOCKDIR to avoid multiple instances of this script.
if ! mkdir 2>/dev/null "$LOCKDIR"; then
    exit 1
fi

trap "rm -rf $LOCKDIR" 0 1 2 15

if test ."$status" = .'up'; then

    # Wait until connected to the Internet.
    if test ."$($NMCLI networking connectivity)" != .'full'; then
        sleep 5
        if test ."$($NMCLI networking connectivity check)" != .'full'; then
            exit 1
        fi
    fi

    # Make every WiFi interface without a profile an access point.
    mapfile -t wifi_interfaces < <(get_managed_interfaces wifi)

    declare -i i=0
    for wifi_interface in "${wifi_interfaces[@]}"; do
        profile=$(
            $NMCLI --terse --fields GENERAL.CONNECTION  device show "$wifi_interface" |
                $AWK -F: '{ print $2 }'
               )
        if test ."$profile" = .''; then
            $ACCESS_POINT "$wifi_interface" "revo-${wifi_interface}" "revo-${wifi_interface}" "revo-${wifi_interface}" 'a' "10.$(( 100 + i++ )).0.1/24"
        fi
    done
fi
