#!/usr/bin/env bash
#
: ${CURL_CMD:=/usr/bin/curl}
: ${GIT_CMD:=/usr/bin/git}
: ${HEAD_CMD:=/usr/bin/head}
: ${MKDIR_CMD:=/bin/mkdir}
: ${SED_CMD:=/bin/sed}
: ${TAR_CMD:=/usr/bin/tar}
: ${TR_CMD:=/usr/bin/tr}
: ${UNAME_CMD:=/bin/uname}

get-latest-tag ()
{
    local url=$1

    $SED_CMD -e 's;.*/;;' <(
        $GIT_CMD ls-remote --sort="-v:refname" "$url" |
            $HEAD_CMD -1 \
                || true
    )
}

get-arch ()
{
    local machine=''

    machine=$($UNAME_CMD -m) || return $?

    case "$machine" in
    x86_64)
        echo amd64
        ;;
    *)
        echo "$machine"
        ;;
    esac
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    declare asdf_url=https://github.com/asdf-vm/asdf

    declare latest_version=''
    declare default_os=''
    declare default_arch=''

    latest_version=$(get-latest-tag "$asdf_url") || exit $?
    default_os=$($UNAME_CMD | $TR_CMD A-Z a-z) || exit $?
    default_arch=$(get-arch) || exit $?

    declare os=${1:-"$default_os"}
    declare arch=${2:-"$default_arch"}
    declare destdir=${3:-"${HOME}/bin"}

    declare release_url=${asdf_url}/releases/download/${latest_version}/asdf-${latest_version}-${os}-${arch}.tar.gz

    $MKDIR_CMD -p ~/bin || exit $?
    $CURL_CMD -sSL "$release_url" | $TAR_CMD -C "$destdir" -zxf - || exit $?
fi
