#!/usr/bin/env bash
#
# @(#) ethernet-link-local
#
# Copyright © 2020, Revolution Robotics, Inc.
#
# This script creates and activates a NetworkManger IPv4LL profile.
#
script_name=${0##*/}
script_dir=${0%/*}

: ${CAT:='/bin/cat'}

source "${script_dir}/ip-funcs"
source "${script_dir}/nm-funcs"

declare -A param=(
    [mode]=ll
)

usage ()
{
    $CAT <<EOF
Usage: $script_name -p PROFILE -i INTERFACE OPTIONS
where OPTIONS are:
  -h|--help      Display help, then exit
  -p|--profile=PROFILE
                 Set connection profile name to PROFILE (e.g., eth0-ll)
  -i|--interface=INTERFACE
                 Set network interface to INTERFACE (e.g., eth0)
  -o|--priority=PRIORITY
                 Set connection priority to PRIORITY
  -r|--retries=RETRIES
                 Set connection retries to RETRIES
EOF
}

declare opts
declare status
declare -r short_opts=h,i:,o:,p:,r:
declare -r long_opts=help,interface:,priority:,profile:,retries:

opts=$(
    getopt --name "$script_name" --options "$short_opts"  \
           --longoptions "$long_opts" -- "$@"
    )

status=$?
if (( status != 0 )); then
    exit $status
fi

eval set -- "$opts"

while true; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -i|--interface)
            param[interface]=$2
            ;;
        -o|--priority)
            param[priority]=$2
            ;;
        -p|--profile)
            param[profile]=$2
            ;;
        -r|--retries)
            param[retries]=$2
            ;;
        --)
            break
            ;;
    esac
    shift 2
done

if test ."${param[profile]}" = .''; then
    echo "$script_name: ${param[profile]}: Not a valid profile name" >&2
    exit 1
fi

validate-interface "${param[interface]}" || exit $?

disconnect-interface "${param[interface]}"
remove-previous-profile "${param[profile]}"
create-ethernet-profile 'param'
activate-profile "${param[profile]}"
