#!/usr/bin/env bash
#
# @(#) wifi-access-point
#
# Copyright © 2020, Revolution Robotics, Inc.
#
# This script creates and activates a NetworkManger WiFi access point
# profile. It's assumed that there's a separate network interface with
# Internet access.
#
script_name=${0##*/}
script_dir=${0%/*}

: ${CAT:='/bin/cat'}

source "${script_dir}/ip-funcs"
source "${script_dir}/nm-funcs"

declare -r DEFAULT_IPV4_ADDR=10.${WIFI_CLASS_B}.0.1/24

declare profile
declare interface=${2:-$(get_managed_interfaces wifi | head -1)}
declare ssid=${3:-"$(hostname)-${interface}"}
declare password=${4:-$(hostname)}
declare wifi_band=${5:-'a'}
declare ipv4_addr=${6:-"$DEFAULT_IPV4_ADDR"}

usage ()
{
    $CAT <<EOF
Usage: $script_name -p PROFILE -i INTERFACE -s SSID -p PASSWORD OPTIONS
where OPTIONS are:
  -h|--help      Display help, then exit
  -p|--profile=PROFILE
                 Set connection profile name to PROFILE (e.g., ${interface}-ap)
  -i|--interface=INTERFACE
                 Set network interface to INTERFACE (default: ${interface})
  -s|--ssid      Set WiFi network name to SSID (default: ${ssid})
  -P|--password=PASSWORD
                 Set WiFi network password to PASSWORD (default: ${password})
  -b|--band=BAND Set WiFi band to either \`a' (5 GHz) or \`bg' (2.4 GHz)
                 (default: ${wifi_band})
  -a|--address=IPv4_ADDR
                 Set IPv4 address/netmask to IPv4_ADDR
                 (default: ${ipv4_addr})
EOF
}

declare opts
declare status
declare -r short_opts=a:,b:,h,i:,P:,p:,s:
declare -r long_opts=address:,band:,help,interface:,password:,profile:,ssid:

opts=$(
    getopt --name "$script_name" --options "$short_opts"  \
           --longoptions "$long_opts" -- "$@"
    )

status=$?
if (( status != 0 )); then
    exit $status
fi

eval set -- "$opts"

while true; do
    case "$1" in
        -a|--address)
            ipv4_addr=$2
            ;;
        -b|--band)
            wifi_band=$2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -i|--interface)
            interface=$2
            ;;
        -P|--password)
            password=$2
            ;;
        -p|--profile)
            profile=$2
            ;;
        -s|--ssid)
            ssid=$2
            ;;
        --)
            break
            ;;
    esac
    shift 2
done

if test ."$profile" = .''; then
    echo "$script_name: $profile: Not a valid profile name" >&2
    exit 1
fi

validate_interface "$interface" || exit $?
validate_wifi_band "$wifi_band" || exit $?
validate_ipv4_network "$interface" "$ipv4_addr" || exit $?

disconnect_interface "$interface"
remove_previous_profile "$profile"
create_wifi_profile ap "$profile" "$interface" "$ssid" "$password" "$wifi_band" "$ipv4_addr"
activate_profile "$profile"
