#!/usr/bin/env bash
#
# @(#) run-roadrunner-container
#
# Copyright © 2021-2023 Revolution Robotics, Inc.
#
# This script runs an interactive bash shell in a container with an
# external volume mounted at the given container mount point.
#
: ${BUILDAH_CMD:='/usr/bin/buildah'}
: ${CAT_CMD:='/bin/cat'}
: ${HEAD_CMD:='/usr/bin/head'}
: ${LS_CMD:='/bin/ls'}
: ${PODMAN_CMD:='/usr/bin/podman'}
: ${SED_CMD:='/usr/bin/sed'}
: ${SORT_CMD:='/usr/bin/sort'}
: ${SUDO_CMD:='/usr/bin/sudo'}

validate-image-reference ()
{
    local image_reference=$1

    if test ."$image_reference" = .''; then
        echo "${FUNCNAME[0]}: Missing image reference" >&2
        return 1
    fi

    local image_id=''

    image_id=$(
        $SUDO_CMD $BUILDAH_CMD images -n --filter=reference="$image_reference" \
                  --format="{{.ID}}"
            ) || return $?

    if test ."$image_id" = .''; then
        echo "${FUNCNAME[0]}: ${image_reference}: No matching images" >&2
        return 2
    fi

    echo "$image_id"
}

validate-host-volume ()
{
    local host_dir=$1
    local volume_name=$2

    if test ."$volume_name" = .'' -o ! -d "${host_dir}/${volume_name}"; then
        volume_name=$(
            $LS_CMD -d "${host_dir}/"* |
                $SORT_CMD -Vr |
                $HEAD_CMD -1 |
                $SED_CMD -e 's;.*/;;'
            ) || return $?

        if test ."$volume_name" = .''; then
            echo "${FUNCNAME[0]}: ${host_dir}: No volumes found" >&2
            return 1
        fi
    fi

    local dest_dir=${host_dir}/${volume_name}

    if test ! -d "$dest_dir"; then
        echo "${FUNCNAME[0]}: ${dest_dir}: No such file or directory" >&2
        return 1
    fi

    echo "$dest_dir"
}

run-container-image ()
{
    local image_id=$1
    local dest_dir=$2
    local mount_point=$3

    local container=''

    container=$(
        $SUDO_CMD $BUILDAH_CMD images -n --format="{{.Name}}" "$image_id"
             ) || return $?

    $CAT_CMD >&2 <<EOF
Container: ${container}
Filesystem: ${dest_dir}
Mount point: ${mount_point}
EOF

    $SUDO_CMD $PODMAN_CMD run -it --rm --privileged --entrypoint=/bin/bash \
          -v "${dest_dir}:${mount_point}:rshared,rbind,exec,dev,suid,rw" \
          "$image_id"
}

reset-window-title ()
{
    printf "\e]0;$USER@${HOSTNAME%%.*}\a"
}

if test ."$0" = ."${BASH_SOURCE[0]}"; then
    set -o pipefail

    declare volume_name=$1
    declare host_dir=${2:-'/opt/src/revo/releases/roadrunner'}
    declare image_reference=${3:-'localhost/roadrunner-debian-builder:latest'}
    declare mount_point=${4:-'/root/roadrunner-debian'}

    if test ."$volume_name" = .''; then
        volume_name=$(
            $LS_CMD -d "${host_dir}/"* |
                $SORT_CMD -Vr |
                $HEAD_CMD -1 |
                $SED_CMD -e 's;.*/;;'
                   ) || return $?
    fi

    declare image_id
    declare dest_dir

    image_id=$(validate-image-reference "$image_reference") || exit $?
    dest_dir=$(validate-host-volume "$host_dir" "$volume_name") || exit $?

    declare status=0

    echo "image_id: ${image_id}" >&2
    echo "dest_dir: ${dest_dir}" >&2
    echo "mount_point: ${mount_point}" >&2
    read -n 1 -p 'Run container [Y|n]? ' run_container

    if test ."$run_container" = .'n'; then
        exit
    fi

    run-container-image "$image_id" "$dest_dir" "$mount_point" || status=$?
    reset-window-title
    exit $exit_status
fi
